version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3307
      DB_DATABASE: root
      DB_USERNAME: root
      DB_PASSWORD: 
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      SANCTUM_STATEFUL_DOMAINS: localhost
      SESSION_DOMAIN: localhost
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3307"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: